Table "dbo"."BUSINESS" {
  "ID" bigint(19) [pk, not null, increment]
  "CODE_LICENSE" varchar(5) [not null]
  "LICENSE" varchar(80)
  "BUSINESS_RUC" varchar(11) [not null]
  "BUSINESS_START_DATE" date [not null]
  "BUSINESS_EXERCISE" varchar(4)
  "COMPANY_NAME" varchar(250)
  "BUSINESS_NAME" varchar(250) [not null]
  "ABOUT_BUSINESS" text
  "WEB_COMPANY" varchar(100)
  "IS_MAIN_BUSINESS" bit
  "IS_VERIFIED" bit
  "BUSINESS_ADDRESS" varchar(250)
  "BUSINESS_COUNTRY" varchar(45)
  "DEPARTMENT" varchar(150) [not null]
  "PROVINCE" varchar(250) [not null]
  "DISTRICT" varchar(250) [not null]
  "BUSINESS_PHONE" varchar(12)
  "BUSINESS_EMAIL" varchar(150)
  "BUSINESS_LEGAL_REPRE" varchar(250)
  "LEGAL_DOCUMENT_TYPE" bigint(19)
  "LEGAL_DOCUMENT" varchar(20)
  "LEGAL_FIRM" varchar(300)
  "FILE_RUC" varchar(300)
  "FILE_COMPLIANCE_CERTIFICATE" varchar(300)
  "CURRENCY_MAIN" bigint(19)
  "CURRENCY_SECONDARY" bigint(19)
  "BUSINESS_LOGO" varchar(300)
  "RETENTION_AGENT" char(1)
  "PERCEPTION_AGENT" char(1)
  "PRICOS" char(1)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."DOCUMENT_TYPE" {
  "DOCUMENT_TYPE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "SUNAT_CODE" varchar(1) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "ABRV" varchar(10)
  "CREATE_USER" int(10) [not null]
  "CREATE_DATE" datetime
  "UPDATE_USER" int(10)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."CURRENCY" {
  "ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CURRENCY_CODE" varchar(2) [not null]
  "CURRENCY_CODE_SUNAT" varchar(4) [not null]
  "CURRENCY_NAME" varchar(150) [not null]
  "CURRENCY_SYMBOL" varchar(5) [not null]
  "CREATE_USER" int(10) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" int(10)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."ADDRESS_CLIENTS" {
  "ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CLIENTS_ID" bigint(19) [not null]
  "MAIN_ADDRESS" bit
  "ADRRESS" varchar(550)
  "DEPARTMENT" varchar(10)
  "PROVINCE" varchar(10)
  "DISTRICT" varchar(10)
  "UBIGEO" varchar(10)
  "CREATE_USER" int(10) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" int(10)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."ADDRESS_BUSINESS" {
  "ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "LABEL" varchar(50)
  "MAIN_ADDRESS" bit
  "ADRRESS" varchar(550)
  "DEPARTMENT" varchar(10)
  "PROVINCE" varchar(10)
  "DISTRICT" varchar(10)
  "UBIGEO" varchar(10)
  "CREATE_DATE" datetime [not null]
  "CREATE_USER" int(10) [not null]
  "UPDATE_USER" int(10)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."TAXES" {
  "TAXES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."JOB_TITLE" {
  "JOB_TITLE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "AREA_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(300) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."AREA" {
  "AREA_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(300) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
  "INTERNAL_VISIBILITY_ID" bigint(19)
}

Table "dbo"."MODULES_PERMISSIONS" {
  "MODULES_PERMISSIONS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "MODULES_ID" bigint(19) [not null]
  "PERMISSIONS_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PROFILES" {
  "PROFILES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "PROFILES_NAME" varchar(250) [not null]
  "PROFILES_DESC" varchar(250)
  "CREATE_USER" int(10) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" int(10)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PROFILES_PERMISSIONS" {
  "PROFILES_PERMISSIONS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "PROFILES_ID" bigint(19) [not null]
  "MODULES_PERMISSIONS_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1)
}

Table "dbo"."PARENT_MODULES" {
  "PARENT_MODULES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [unique, not null]
  "CODE" varchar(80) [unique, not null]
  "TITLE" varchar(60) [not null]
  "STICKY_BOTTOM" bit
  "ICON_KEY" varchar(50)
  "ORDER_NO" int(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."MODULES" {
  "MODULES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [unique, not null]
  "PARENT_MODULES_ID" bigint(19)
  "PARENT_ID" bigint(19)
  "CODE" varchar(80) [unique]
  "LABEL" varchar(50) [unique, not null]
  "PATH" varchar(450)
  "MODULES_DESCRIPTION" varchar(50)
  "ICON_KEY" varchar(50)
  "ORDER_NO" int(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."DEPARTAMENT" {
  "DEPARTMENT_ID" int(10) [pk, not null, increment]
  "DEPARTAMENT_NAME" varchar(50) [not null]
}

Table "dbo"."PROVINCE" {
  "PROVINCE_ID" int(10) [pk, not null, increment]
  "DEPARTAMENT_ID" int(10) [not null]
  "PROVINCE_NAME" varchar(50) [not null]
}

Table "dbo"."DISTRICT" {
  "DISTRICT_ID" int(10) [pk, not null, increment]
  "DEPARTAMENT_ID" int(10) [not null]
  "PROVINCE_ID" int(10) [not null]
  "DISTRICT_NAME" varchar(50) [not null]
}

Table "dbo"."PENSION" {
  "PESION_ID" bigint(19) [pk, not null, increment]
  "PENSDION_NAME" varchar(150)
  "COMMISION" varchar(10)
}

Table "dbo"."EXCHANGE_RATE" {
  "EXCHANGE_RATE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "PURCHASE_TYPE" decimal(10,3)
  "SALE_TYPE" decimal(10,3)
  "DATE_FXRATE" date [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PAYMENT_TYPE" {
  "PAYMENT_TYPE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CODE" varchar(2) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."UNIT_OF_MEASURE" {
  "UOM_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CODE_SUNAT" varchar(15) [not null]
  "SYMBOL" varchar(15) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."TAX_AFF_TYPE" {
  "TAX_AFF_TYPE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CODE" varchar(2) [not null]
  "DESCRIPTION" varchar(250) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."CONCEPT_GROUPS" {
  "CONCEPT_GROUPS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CODE" varchar(10) [not null]
  "DESCRIPTION" varchar(60) [not null]
  "CONCEPT_TYPE_ID" int(10) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."CONCEPT_TYPE" {
  "CONCEPT_TYPE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."ACCOUNT_LEVEL" {
  "ACCOUNT_LEVEL_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CODE" varchar(3) [not null]
  "DESCRIPTION" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."ACCOUNT_TYPE" {
  "ACCOUNT_TYPE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CODE" varchar(3) [not null]
  "DESCRIPTION" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."TYPE_ANALYSIS" {
  "TYPE_ANALYSIS_ID" int(10) [pk, not null, increment]
  "CODE" varchar(3) [not null]
  "DESCRIPTION" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."AUXILIARY_TYPE" {
  "AUXILIARY_TYPE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CODE" varchar(3) [not null]
  "DESCRIPTION" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."SERIES" {
  "SERIES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "PAYMENT_TYPE_ID" bigint(19) [not null]
  "SERIES_NAME" varchar(20) [not null]
  "CORRELATIVE" bigint(19) [not null]
  "USED" char(1) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."ACCOUNT_PLAN" {
  "ACCOUNT_PLAN_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "ACCOUNT_CODE" varchar(150) [not null]
  "DESCRIPTION" varchar(350) [not null]
  "ACCOUNT_TYPE_ID" int(10)
  "ACCOUNT_LEVEL_ID" int(10)
  "TYPE_ANALYSIS_ID" int(10)
  "CURRENCY_ID" bigint(19)
  "AUXILIARY_TYPE_ID" int(10)
  "DIFFERENCE_CHANGE" varchar(5)
  "DOC_CONTROL" varchar(5)
  "ACCOUNT_AMARRE_DEBIT" bigint(19)
  "ACCOUNT_CREDIT_ACCOUNT" bigint(19)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."CONCEPTS" {
  "CONCEPTS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CONCEPT_GROUPS_ID" bigint(19) [not null]
  "ACCOUNT_PLAN_ID" bigint(19)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."CONTACT_TYPE" {
  "CONTACT_TYPE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."COST_CENTERS" {
  "COST_CENTERS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."LEADS_QUALIFICATIONS" {
  "LEADS_QUALIFICATIONS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."CONTACTS_TYPE" {
  "CONTACTS_TYPE_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(60) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."LEADS_SOURCES" {
  "LEADS_SOURCES_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."LEADS_STATUS" {
  "LEADS_STATUS_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."USERS_PREFERENCES" {
  "USERS_ID" bigint(19) [pk, not null]
  "BUSINESS_ID" bigint(19) [not null]
  "EMAIL_NOTIF" bit [default: 1]
  "PUSH_NOTIF" bit [default: 0]
  "LENGUAGE" nvarchar(50) [default: `N'es'`]
  "TIMEZONE" nvarchar(50) [default: `N'America/Lima'`]
  "THEME" nvarchar(50) [default: `N'system'`]
  "DENSITY" nvarchar(50) [default: `N'compact'`]
  "UPDATE_DATE" datetime [not null]
}

Table "dbo"."CATEGORIES" {
  "CATEGORIES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PRODUCT_LINES" {
  "PRODUCT_LINES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CATEGORIES_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."BUSINESS_LINE" {
  "BUSINESS_LINE_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESC_LINE" varchar(30) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PROCESS_TYPE" {
  "PROCESS_TYPE_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESC_TYPE" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."STATE_OPPORTUNITY" {
  "STATE_OPPORTUNITY_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "STATE_COLOR" varchar(10)
  "STATE_DESC" varchar(100) [not null]
  "NUM_PERC_PRO" int(10) [not null]
  "NUM_ORDER" int(10) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."WORKER" {
  "WORKER_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "AREA_ID" bigint(19) [not null]
  "JOB_TITLE_ID" bigint(19) [not null]
  "PREV_JOB" varchar(100)
  "WORKER_NAME" varchar(350) [not null]
  "WORKER_LAST_NAME" varchar(350) [not null]
  "DOCUMENT_TYPE_ID" bigint(19) [not null]
  "WORKER_DOCUMENT" varchar(15) [not null]
  "DEPARTMENT_ID" bigint(19)
  "PROVINCIA_ID" bigint(19)
  "DISTRICT_ID" bigint(19)
  "ADDRESS" varchar(300)
  "PHONE" varchar(15)
  "EMAIL" varchar(300)
  "BIRTHDATE" date
  "DATE_ENTRY" date
  "DATE_CES" date
  "PENSION_ID" bigint(19)
  "IND_COMISSE_TYPE" bit
  "BANK_ID" bigint(19)
  "CC_BANK" varchar(30)
  "CCI_BANK" varchar(30)
  "SALARY" decimal(10,2)
  "NUMBER_CHILDREN" varchar(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1)
}

Table "dbo"."MOV_CLAS" {
  "MOV_CLAS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."MOV_OPER" {
  "MOV_OPER_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."MOV_PER" {
  "MOV_PER_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."MOV_SUNAT" {
  "MOV_SUNAT_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."MOV_VIS" {
  "MOV_VIS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."BRANDS" {
  "BRANDS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."MOVEMENT_TYPES" {
  "MOVEMENT_TYPES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CODE" char(3) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "MOV_CLAS_ID" bigint(19) [not null]
  "MOV_OPER_ID" bigint(19) [not null]
  "MOV_PER_ID" bigint(19) [not null]
  "MOV_SUNAT_ID" bigint(19) [not null]
  "MOV_VIS_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PRODUCT_TYPES" {
  "PRODUCT_TYPES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."WAREHOUSES" {
  "WAREHOUSES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "ADDRESS" varchar(50) [not null]
  "DEPARTAMENT_ID" bigint(19) [not null]
  "PROVINCE_ID" bigint(19) [not null]
  "DISTRICT_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."SECTOR" {
  "SECTOR_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESC_SECTOR" varchar(350) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."BANK" {
  "BANK_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(60) [not null]
  "ABRV" varchar(5) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."REASON_REJECTION" {
  "REASON_REJECTION_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESC_REASON" varchar(250) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."BOXES" {
  "BOXES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CURRENCY_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."ACCOUNT" {
  "ACCOUNT_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CURRENCY_ID" bigint(19) [not null]
  "BANK_ID" bigint(19) [not null]
  "ACCOUNT_PLAN_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PROJECT_STATUS" {
  "PROJECT_STATUS_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "STATE_DESC" varchar(250) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."SUPPLIER_GROUPS" {
  "SUPPLIER_GROUPS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(100) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PM_CONDITION" {
  "PM_CONDITION_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PM_VIS" {
  "PM_VIS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PAYMENT_METHOD" {
  "PAYMENT_METHOD_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(70) [not null]
  "DAYS" varchar(2) [not null]
  "PM_CONDITION_ID" bigint(19) [not null]
  "PM_VIS_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."STATE_TASK" {
  "STATE_TASK_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "STATE_COLOR" varchar(100)
  "STATE_DESC" varchar(50) [not null]
  "NUM_PERC_PRO" int(10)
  "NUM_ORDER" int(10) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PRIORITY_STATE" {
  "PRIORITY_STATE_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "COLOR" varchar(50)
  "PRIORITY_DESC" varchar(50)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."AUDIT_ENTITY" {
  "ENTITY_CODE" smallint(5) [pk, not null]
  "ENTITY_NAME" varchar(50) [unique, not null]
}

Table "dbo"."AUDIT_ACTION" {
  "ACTION_CODE" smallint(5) [pk, not null]
  "ACTION_NAME" varchar(50) [unique, not null]
}

Table "dbo"."AUDIT_EVENT_DIFF" {
  "EVENT_ID" bigint(19) [pk, not null]
  "COLUMN_NAME" sysname(256) [pk, not null]
  "OLD_VALUE" nvarchar(4000)
  "NEW_VALUE" nvarchar(4000)
}

Table "dbo"."ACTIVITY_TYPE" {
  "ACTIVITY_TYPE_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "ACTIVITY_ICON" varchar(50) [not null]
  "ACTIVITY" varchar(250) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."AUDIT_DDL" {
  "DDL_ID" bigint(19) [pk, not null, increment]
  "PostTime" datetime2 [not null, default: `sysutcdatetime()`]
  "EventType" nvarchar(128) [not null]
  "ObjectName" nvarchar(256)
  "ObjectType" nvarchar(25)
  "TSQLCommand" nvarchar(MAX)
  "LoginName" sysname(256)
  "HostName" sysname(256)
  "AppName" nvarchar(256)
  "ClientIP" varchar(48)
}

Table "dbo"."ACTIVITY_STATE" {
  "ACTIVITY_STATE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "STATE_ICON" varchar(50)
  "STATE_COLOR" varchar(20)
  "STATE_DESC" varchar(100) [not null]
  "ORDER_STATE" int(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [default: `getdate()`]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" bit [default: 1]
}

Table "dbo"."ACTIVITY" {
  "ACTIVITY_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19)
  "PROJECT_ID" bigint(19)
  "ACTIVITY_TYPE_ID" int(10)
  "WORKER_OWNER_ID" bigint(19)
  "WORKER_SENDER_ID" bigint(19)
  "ACTIVITY_STATE_ID" int(10)
  "ACTIVITY_STATE_STAGE" int(10)
  "NUM_PROGRESS_STAGE" int(10)
  "NUM_PROGRESS_PROJECT" int(10)
  "ACTIVITY_MESSAGE" varchar(250)
  "MESSAGE_ADIC" varchar(250)
  "MESSAGE_DATE" date
  "FINISH_DATE" date
  "START_TIME" time
  "FINISH_TIME" time
  "IND_ENTITY" int(10)
  "IND_AUTO" bit
  "IND_CANCELL" bit
  "IND_COMM" bit
  "IND_PRIORITY_ACT" int(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PERIODS" {
  "PERIODS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "END_DATE" date [not null]
  "EXERCISES_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_DATE" bigint(19)
  "UPDATE_USER" datetime
  "STATUS" char(1) [not null]
  "IND_BLOCK" bit [not null, default: 1]
}

Table "dbo"."EXERCISES" {
  "EXERCISES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "END_DATE" date [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_DATE" bigint(19)
  "UPDATE_USER" datetime
  "STATUS" char(1) [not null]
  "IND_BLOCK" bit [not null, default: 0]
}

Table "dbo"."STATE_PRE_SALE" {
  "STATE_PRE_SALE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "STATE_COLOR" varchar(50)
  "STATE_DESC" varchar(100) [not null]
  "NUM_PERC_PRO" int(10) [not null]
  "NUM_ORDER" int(10) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PRE_SALE_PROYECTS" {
  "PRE_SALE_PROYECTS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(100) [not null]
  "CLIENTS_ID" bigint(19) [not null]
  "CONTACTS_CRM_ID" bigint(19) [not null]
  "SELLER_ID" bigint(19)
  "SUPERVISOR_ID" bigint(19)
  "SSOMA_ID" bigint(19)
  "TEC_LEADER_ID" bigint(19)
  "OPPORTUNITY_ID" bigint(19) [not null]
  "STATE_PRE_SALE_ID" bigint(19) [not null]
  "QUOTATION_NUMBER_ID" bigint(19)
  "ORDER_NUMBER_ID" bigint(19)
  "ORDER_DATE" datetime
  "START_DATE" datetime [not null]
  "END_DATE" datetime [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
  "PROYECT_NUM" varchar(15) [not null, default: '']
  "PROYECT_NUM_INT" int(10)
  "PROJECT_TEAM" bigint(19)
  "STATE_GENERAL_ID" bigint(19)
  "STATE_OPPORTUNITY_ID" bigint(19)
  "RESPONSIBLE_ID" bigint(19)
}

Table "dbo"."AUDIT_EVENT" {
  "EVENT_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19)
  "ENTITY_CODE" smallint(5) [not null]
  "ENTITY_ID" bigint(19)
  "ACTION_CODE" smallint(5) [not null]
  "RELATED_ID" bigint(19)
  "DESCRIPTION" varchar(300)
  "CHANGED_BY" varchar(100)
  "CHANGED_AT" datetime2 [not null, default: `sysutcdatetime()`]
  "SOURCE_APP" varchar(60)
  "CHANGED_IP" varchar(48)
  "ENTITY_PROJ_ID" bigint(19)

  Indexes {
    (BUSINESS_ID, CHANGED_AT) [type: nonclustered, name: "IX_AUDIT_EVENT_Business"]
    (ENTITY_CODE, ENTITY_ID, CHANGED_AT) [type: nonclustered, name: "IX_AUDIT_EVENT_Entity"]
  }
}

Table "dbo"."USERS" {
  "USERS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "WORKER_ID" bigint(19)
  "USERS_NAME" varchar(450) [not null]
  "USERS_LAST_NAME" varchar(450) [not null]
  "USERS_CODE" varchar(50)
  "DOCUMENT_TYPE_ID" bigint(19) [not null]
  "USERS_DOCUMENT" varchar(20) [not null]
  "USERS_EMAIL" varchar(150)
  "PROFILES_ID" bigint(19)
  "USER_PHOTO" varchar(350)
  "USERS_PASSWORD" varchar(450) [not null]
  "USERS_SALT" varchar(450) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PROJECT_TEAM" {
  "PROJECT_TEAM_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "PROJECT_ID" bigint(19)
  "WORKER_ID" bigint(19)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."OPPORTUNITY_COMMENTS_READ" {
  "BUSINESS_ID" bigint(19) [pk, not null]
  "OPPOR_ID" bigint(19) [pk, not null]
  "USERS_ID" bigint(19) [pk, not null]
  "LAST_READ_COMMENT_ID" bigint(19) [not null]
  "LAST_READ_AT" datetime2 [not null, default: `sysdatetime()`]
}

Table "dbo"."NOTIFICATIONS" {
  "NOTIFICATION_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "USERS_ID" bigint(19) [not null]
  "TITLE" varchar(120) [not null]
  "MESSAGE" varchar(500) [not null]
  "MODULE" varchar(50) [not null]
  "ENTITY" varchar(50)
  "ENTITY_ID" bigint(19)
  "LINK_URL" varchar(200)
  "TYPE" varchar(20) [not null]
  "READ_AT" datetime
  "CREATED_AT" datetime [not null, default: `getdate()`]
  "CREATED_BY" bigint(19) [not null]
}

Table "dbo"."CLIENT_ACTIVITY_HISTORY" {
  "EVENT_ID" bigint(19) [pk, not null, increment]
  "CLIENTS_ID" bigint(19) [not null]
  "BUSINESS_ID" bigint(19) [not null]
  "MODULE_CODE" varchar(50) [not null]
  "ACTION_CODE" varchar(50) [not null]
  "DESCRIPTION" nvarchar(300)
  "CREATED_AT" datetime2 [not null, default: `sysutcdatetime()`]
  "USER_ID" bigint(19) [not null]
  "RELATED_ID" bigint(19)
}

Table "dbo"."CLIENTS" {
  "CLIENTS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DOCUMENT_TYPE_ID" bigint(19) [not null]
  "DOCUMENTS" varchar(50) [not null]
  "CLIENTS_NAME" varchar(450) [not null]
  "CLIENT_COMPANY" varchar(550)
  "CLIENT_ADDRESS" varchar(550) [not null]
  "CLIENT_PHONE" varchar(50)
  "WORKER_ID" bigint(19)
  "DEPARTAMENT_ID" bigint(19)
  "PROVINCE_ID" bigint(19)
  "DISTRICT_ID" bigint(19)
  "PROCESS_TYPE_ID" bigint(19)
  "SECTOR_ID" bigint(19)
  "LEADS_SOURCES_ID" bigint(19)
  "LEADS_STATUS_ID" bigint(19)
  "LEADS_QUALIFICATIONS_ID" bigint(19)
  "WEB" varchar(250)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."CONTACTS_CRM" {
  "CONTACTS_CRM_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "CONTACT_NAME" varchar(50) [not null]
  "JOB_TITLE" varchar(50) [not null]
  "PHONE" varchar(50)
  "MOVIL" varchar(15)
  "EMAIL" varchar(550) [not null]
  "WORKER_ID" bigint(19) [not null]
  "CLIENTS_ID" bigint(19) [not null]
  "LEADS_SOURCES_ID" bigint(19)
  "CONTACT_TYPE_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."PERMISSIONS" {
  "PERMISSIONS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "PERMISSIONS_CODE" varchar(550)
  "PERMISSIONS_NAME" varchar(150) [not null]
  "PERMISSIONS_DESC" varchar(150)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."VIABILITY_STATUS" {
  "VIABILITY_STATUS_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "VIABILITY_STATUS" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" varchar(1) [not null]
}

Table "dbo"."NOTIF_RULES" {
  "RULE_ID" bigint(19) [pk, not null, increment]
  "EVENT_CODE" varchar(100) [not null]
  "TARGET_TYPE" varchar(50) [not null]
  "TARGET_VALUE" varchar(100)
  "ACTIVE" bit [not null, default: 1]
}

Table "dbo"."NOTIF_RULE_FILTERS" {
  "FILTER_ID" bigint(19) [pk, not null, increment]
  "RULE_ID" bigint(19) [not null]
  "FILTER_FIELD" varchar(50) [not null]
  "FILTER_VALUE" varchar(50) [not null]
}

Table "dbo"."PRODUCTS" {
  "PRODUCTS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "BAR_CODE" varchar(500)
  "PART_NUM" varchar(100)
  "DESCRIPTION" varchar(100) [not null]
  "PRODUCT_LINES_ID" bigint(19) [not null]
  "BRANDS_ID" bigint(19) [not null]
  "PRODUCT_TYPES_ID" bigint(19) [not null]
  "UOM_ID" bigint(19) [not null]
  "STOCK_MIN" int(10)
  "FILES" varchar(350)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
  "CATEGORIES_ID" bigint(19)
}

Table "dbo"."EMAIL_OUTBOX" {
  "OUTBOX_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "EVENT_CODE" varchar(60) [not null]
  "TO_EMAIL" varchar(200) [not null]
  "SUBJECT" nvarchar(200) [not null]
  "PAYLOAD_JSON" nvarchar(MAX) [not null]
  "STATUS" varchar(20) [not null, default: 'PENDING']
  "RETRIES" int(10) [not null, default: 0]
  "NEXT_ATTEMPT_AT" datetime [not null, default: `getdate()`]
  "CREATED_AT" datetime [not null, default: `getdate()`]
  "SENT_AT" datetime
  "LAST_ERROR" nvarchar(MAX)
  "TARGET_USER_ID" bigint(19)
  "CC_EMAIL" varchar(200)

  Indexes {
    (STATUS, NEXT_ATTEMPT_AT, RETRIES) [type: nonclustered, name: "IX_EMAIL_OUTBOX_PENDING"]
  }
}

Table "dbo"."OPPOR_COMMENT_AUDIENCE" {
  "COMMENT_ID" bigint(19) [pk, not null]
  "AREA_ID" bigint(19) [pk, not null]
}

Table "dbo"."VISIBILITY_TYPES" {
  "VISIBILITY_ID" bigint(19) [pk, not null]
  "CODE" varchar(50) [unique, not null]
  "NAME" varchar(100) [not null]
}

Table "dbo"."FILE_TRACKING_PRODUCTS" {
  "FILE_TRACKING_PRODUCTS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "PRODUCTS_ID" bigint(19) [not null]
  "FILES" varchar(500) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."GENERAL_STATES" {
  "GENERAL_STATES_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "COLOR_STATE" varchar(50)
  "GENERAL_STATES" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" varchar(1) [not null]
}

Table "dbo"."OPPOR_VIABILITY" {
  "OPPOR_VIABILITY_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_NUM" varchar(15) [not null]
  "OPPOR_DESC" varchar(150) [not null]
  "CLIENTS_ID" bigint(19) [not null]
  "GENERAL_STATES_ID" bigint(19) [not null]
  "STATE_OPPORTUNITY_ID" bigint(19) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."FILE_TRACKING" {
  "FILE_TRACKING_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19)
  "PROJECT_ID" bigint(19)
  "FILE_TYPE" varchar(150)
  "FILE_TITLE" varchar(350)
  "FILE_URL" varchar(550) [not null]
  "RELATIVE_PATH" varchar(550)
  "COMMENT" text
  "CREATE_DATE" datetime [not null]
  "CREATE_USER" bigint(19) [not null]
  "UPDATE_DATE" datetime
  "UPDATE_USER" bigint(19)
  "STATUS" char(1) [not null]
}

Table "dbo"."OPPOR_COMMENTS" {
  "COMMENT_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "MESSAGE" nvarchar(1000) [not null]
  "VISIBILITY_ID" bigint(19)
  "IS_INTERNAL" bit [not null]
  "CREATED_BY" bigint(19) [not null]
  "CREATED_AT" datetime2 [not null, default: `sysdatetime()`]

  Indexes {
    (BUSINESS_ID, OPPOR_ID, CREATED_AT) [type: nonclustered, name: "IX_OPPOR_COMMENTS_OPPOR"]
  }
}

Table "dbo"."ST_OPPOR_DELIVERABLES" {
  "DELIVERABLE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "NAME" nvarchar(200) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "IS_ACTIVE" bit [not null]
}

Table "dbo"."OPPOR_DELIVERABLE_REQUESTS" {
  "REQUEST_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "DELIVERABLE_ID" bigint(19) [not null]
  "COMMENT" nvarchar(500)
  "TASK_ID" bigint(19)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime2 [not null, default: `sysdatetime()`]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime2 [default: `sysdatetime()`]
  "STATUS" char(1) [not null]
}

Table "dbo"."TASKS" {
  "TASKS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19)
  "WORKER_ID" bigint(19)
  "AREA_ID" bigint(19)
  "TITLE" varchar(100) [not null]
  "DESCRIPTION" varchar(400) [not null]
  "END_DATE" date
  "TIME" time
  "STATE_TASK_ID" bigint(19)
  "PRIORITY_STATE_ID" int(10)
  "ENTITY_CODE" char(1)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
  "PROJECT_ID" bigint(19)
  "DELIVERABLE_ID" bigint(19)
  "OBS_ID" bigint(19)
}

Table "dbo"."OPPOR_WATCHERS" {
  "BUSINESS_ID" bigint(19) [pk, not null]
  "OPPOR_ID" bigint(19) [pk, not null]
  "USERS_ID" bigint(19) [pk, not null]
  "CREATED_AT" datetime2 [not null, default: `sysdatetime()`]
}

Table "dbo"."ST_VISIBILITY" {
  "VISIBILITY_ID" bigint(19) [pk, not null, increment]
  "CODE" varchar(50) [not null]
  "DESCRIPTION" nvarchar(200)
}

Table "dbo"."NOTIFICATIONS_OUTBOX" {
  "OUTBOX_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19)
  "USERS_ID" bigint(19)
  "TITLE" varchar(200)
  "MESSAGE" varchar(200)
  "MODULE" varchar(200)
  "ENTITY" varchar(200)
  "ENTITY_ID" varchar(200)
  "LINK_URL" varchar(600)
  "TYPE" varchar(200)
  "CREATED_AT" datetime
  "CREATE_BY" bigint(19)
  "PROCESSED_AT" datetime
}

Table "dbo"."COMMERCIAL_PARAMETERS" {
  "PARAMETERS_COMM_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "PARAMETERS_NAME" varchar(250)
  "MIN_VALUE" int(10)
  "PARAMETERS_VALUE" int(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" varchar(1) [not null]
}

Table "dbo"."VIABILITY" {
  "VIABILITY_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "VIABILITY_SCORE" int(10)
  "COMPLIANCE" int(10)
  "PARTIAL_COMPLIANCE" int(10)
  "NON_COMPLIANCE" int(10)
  "AUTHORITY" int(10)
  "AUTHORITY_DESC" varchar(100)
  "BUDGET" int(10)
  "BUDGET_DESC" varchar(100)
  "NEED" int(10)
  "NEED_DESC" varchar(100)
  "TERM" int(10)
  "TERM_DESC" varchar(100)
  "COMPANY_EXPERIENCE" int(10)
  "COMPANY_EXP_DESC" varchar(100)
  "WORK_EXPERIENCE" int(10)
  "WORK_EXP_DESC" varchar(100)
  "STAFF_EXPERIENCE" int(10)
  "STAFF_EXP_DESC" varchar(100)
  "ABILITY" int(10)
  "ABILITY_DESC" varchar(100)
  "SCHEDULE" int(10)
  "SCHEDULE_DESC" varchar(100)
  "CONTRACT_METHOD" int(10)
  "CONTRACT_METHOD_DESC" varchar(100)
  "REQUIRES_ISOS" int(10)
  "REQUIRES_ISOS_DESC" varchar(100)
  "VIABILITY_STATUS" int(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."TYPE_SUPPLIERS" {
  "TYPE_SUPPLIERS_ID" int(10) [pk, not null, increment]
  "BUSINESS_ID" bigint(19)
  "TS_DESC" varchar(450) [not null]
  "CREATE_USER" bigint(19)
  "CREATE_DATE" datetime
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1)
}

Table "dbo"."MARGEN_TYPE" {
  "MARGEN_TYPE_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "DESCRIPTION" varchar(50) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."SALES_QUOTATION_EGRESS_VER_HDR" {
  "EGRESS_VER_ID" bigint(19) [pk, not null, increment]
  "QUOTATION_VER_ID" bigint(19) [not null]
  "MONTH_NO" int(10) [not null]
  "AMOUNT" decimal(18,2) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime2 [not null, default: `sysdatetime()`]
  "STATUS" bit [not null, default: 1]

  Indexes {
    (QUOTATION_VER_ID, MONTH_NO) [type: nonclustered, name: "IX_EGRESS_HDR_VER"]
  }
}

Table "dbo"."SALES_QUOTATION_EGRESS_VER_LIN" {
  "EGRESS_VER_LIN_ID" bigint(19) [pk, not null, increment]
  "EGRESS_VER_ID" bigint(19) [unique, not null]
  "LINE_NO" int(10) [unique, not null]
  "MONTH_NO" int(10) [not null]
  "AMOUNT" decimal(18,2) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime2 [not null, default: `sysdatetime()`]
  "STATUS" bit [not null, default: 1]

  Indexes {
    (EGRESS_VER_ID, MONTH_NO) [type: nonclustered, name: "IX_EGRESS_LIN_HDR"]
  }
}

Table "dbo"."SYSTEMS" {
  "SYSTEM_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "SYSTEM_NAME" nvarchar(180) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" bit [not null, default: 1]
}

Table "dbo"."PAYMENT_CONDITION" {
  "CONDITION_ID" bigint(19) [pk, not null, increment]
  "CONDITION_NAME" nvarchar(60) [unique, not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" bit [not null, default: 1]
}

Table "dbo"."SALES_QUOTATION_LINE_PLAN_VER_HDR" {
  "LINE_PLAN_ID" bigint(19) [pk, not null, increment]
  "QUOTATION_VER_LIN_ID" bigint(19) [unique, not null]
  "NOTES" nvarchar(200)

  Indexes {
    (LINE_PLAN_ID, QUOTATION_VER_LIN_ID) [type: nonclustered, name: "IX_LINE_PLAN_HDR_LIN"]
  }
}

Table "dbo"."SALES_QUOTATION_LINE_PLAN_VER_LIN" {
  "LINE_PLAN_LIN_ID" bigint(19) [pk, not null, increment]
  "LINE_PLAN_ID" bigint(19) [unique, not null]
  "SEQ_NO" int(10) [not null]
  "PAYMENT_PERCENT" decimal(9,6)
  "PAYMENT_AMOUNT" decimal(18,2)
  "MONTH_NO" int(10) [unique]
  "PAYMENT_NO" int(10) [unique]

  Indexes {
    (SEQ_NO, PAYMENT_PERCENT, PAYMENT_AMOUNT, LINE_PLAN_ID) [type: nonclustered, name: "IX_LINE_PLAN_LIN_PLAN"]
  }
}

Table "dbo"."SALES_QUOTATION_SERVICE_CHECK_VER" {
  "SERVICE_CHECK_ID" bigint(19) [pk, not null, increment]
  "QUOTATION_VER_ID" bigint(19) [unique, not null]
  "QUOTATION_AMOUNT" decimal(18,2) [not null]
  "SCHEDULE_AMOUNT" decimal(18,2) [not null]
  "DIFFERENCE_AMOUNT" decimal(18,2) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime2 [not null, default: `sysdatetime()`]
}

Table "dbo"."SALES_QUOTATION_VER_HDR" {
  "QUOTATION_VER_ID" bigint(19) [pk, not null, increment]
  "QUOTATION_ID" bigint(19) [unique, not null]
  "VERSION_NO" int(10) [unique, not null]
  "IS_ACTIVE" bit [not null, default: 1]
  "VER_STATUS_ID" bigint(19)
  "SUB_TOTAL" decimal(18,2) [not null, default: 0]
  "DISCOUNT_AMOUNT" decimal(18,2) [not null, default: 0]
  "TAX_AMOUNT" decimal(18,2) [not null, default: 0]
  "TOTAL_AMOUNT" decimal(18,2) [not null, default: 0]
  "NOTES" varchar(500)
  "SALES_TOTAL" decimal(18,2)
  "COST_TOTAL" decimal(18,2) [not null, default: 0]
  "UTILITY_TOTAL" decimal(18,2) [not null, default: 0]
  "MARGIN_PERCENT" decimal(9,2) [not null, default: 0]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime2 [not null, default: `sysdatetime()`]

  Indexes {
    (QUOTATION_ID, IS_ACTIVE) [type: nonclustered, name: "IX_SALES_QUOTATION_VER_HDR_QUOTATION_ACTIVE"]
  }
}

Table "dbo"."SALES_QUOTATION_HDR" {
  "QUOTATION_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "CLIENTS_ID" bigint(19) [not null]
  "QUOTATION_NO" nvarchar(50)
  "QUOTATION_STATUS_ID" bigint(19)
  "CURRENCY_ID" bigint(19)
  "EXCHANGE_RATE" decimal(18,3)
  "PM_CONDITION_ID" bigint(19)
  "OFFER_VALIDITY" int(10)
  "START_DATE" date
  "FINISH_DATE" date
  "CURRENT_VERSION_NO" int(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" date
  "STATUS" char(1) [not null]

  Indexes {
    (BUSINESS_ID, CLIENTS_ID) [type: nonclustered, name: "IX_SALES_QUOTATION_HDR_BUSINESS_CLIENT"]
    (BUSINESS_ID, CLIENTS_ID, CREATE_DATE) [type: nonclustered, name: "IX_SALES_QUOTATION_HDR_BUSINESS_CLIENT_DATE"]
    (BUSINESS_ID, OPPOR_ID) [type: nonclustered, name: "IX_SALES_QUOTATION_HDR_BUSINESS_OPPOR"]
  }
}

Table "dbo"."SALES_QUOTATION_MARGIN_VER" {
  "QUOTATION_MARGIN_ID" bigint(19) [pk, not null, increment]
  "QUOTATION_VER_ID" bigint(19) [unique, not null]
  "MARGIN_TYPE_ID" bigint(19) [unique, not null]
  "MARGIN_RATE" decimal(9,6) [not null]
  "MARGIN_AMOUNT" decimal(18,2)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime2 [not null, default: `sysdatetime()`]
}

Table "dbo"."SUPPLIERS" {
  "SUPPLIERS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "TYPE_SUPPLIERS_ID" int(10)
  "SUPPLIERS_GROUPS_ID" bigint(19)
  "PAYMENT_TYPE_ID" bigint(19)
  "PAYMENT_METHOD_ID" bigint(19)
  "DOCUMENT_TYPE_ID" bigint(19)
  "DEPARTAMENT_ID" bigint(19)
  "PROVINCE_ID" bigint(19)
  "DISTRICT_ID" bigint(19)
  "DOCUMENT_NUMBER" varchar(100)
  "SUPPLIER_NAME" varchar(50)
  "CONTACT_NAME" varchar(50)
  "ADDRESS" varchar(50)
  "PHONE" varchar(20)
  "MOVIL" varchar(20)
  "EMAIL" varchar(40)
  "RETAINER_AGENT" char(1)
  "PERCEPTION_AGENT" char(1)
  "DETRACTION_AGENT" char(1)
  "FOREIGN_AGENT" char(1)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."SUB_TASKS" {
  "SUB_TASKS_ID" bigint(19) [pk, not null, increment]
  "TASKS_ID" bigint(19) [not null]
  "BUSINESS_ID" bigint(19) [not null]
  "WORKER_ID" bigint(19)
  "AREA_ID" bigint(19)
  "TITLE" varchar(100) [not null]
  "DESCRIPTION" varchar(400) [not null]
  "END_DATE" date
  "TIME" time
  "STATE_TASK_ID" bigint(19)
  "PRIORITY_STATE_ID" int(10)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."QUOTATION_STATUS" {
  "QUOTATION_STATUS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "QUOTATION_DESC" varchar(350) [not null]
  "QUOTATION_COLOR" varchar(250)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."VER_STATUS" {
  "VER_STATUS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "VER_DESC" varchar(350) [not null]
  "VER_COLOR" varchar(150)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."SALES_QUOTATION_VER_LIN" {
  "QUOTATION_VER_LIN_ID" bigint(19) [pk, not null, increment]
  "QUOTATION_VER_ID" bigint(19) [unique, not null]
  "LINE_NO" int(10) [unique, not null]
  "LINE_TYPE" varchar(10) [not null, default: 'ITEM']
  "PARENT_QUOTATION_VER_LIN_ID" bigint(19)
  "DISPLAY_NO" nvarchar(20)
  "LEVEL_NO" int(10) [not null, default: 1]
  "IS_ROLLUP" bit [not null, default: 0]
  "ITEM_ID" bigint(19)
  "PRODUCTS_ID" bigint(19)
  "DESCRIPTION" nvarchar(4000) [not null]
  "PRODUCTS_TYPE_ID" bigint(19)
  "UOM_ID" bigint(19)
  "BRAND_ID" bigint(19)
  "MODEL" nvarchar(300)
  "QTY" decimal(18,6) [default: 0]
  "UNIT_PRICE" decimal(18,6) [default: 0]
  "TOTAL_PRICE" decimal(18,6) [default: 0]
  "DISCOUNT_AMOUNT" decimal(18,6) [default: 0]
  "TAX_AMOUNT" decimal(18,6) [default: 0]
  "LINE_TOTAL" decimal(18,6) [default: 0]
  "IS_PRESALES" bit [not null, default: 0]
  "IS_BOLD" bit [not null, default: 0]
  "STATUS" bit [not null, default: 1]
  "UNIT_COST" decimal(18,2)
  "LINE_COST_TOTAL" decimal(18,2)
  "UNIT_SALE_PRICE" decimal(18,2)
  "LINE_SALE_TOTAL" decimal(18,2)
  "MARGIN_PERCENT_LINE" decimal(9,6)
  "PRESALES_ASSIGNED_ID" bigint(19)
  "PRESALES_ASSIGNED_TO" nvarchar(150)
  "SYSTEM_ID" bigint(19)
  "SUPPLIERS_ID" bigint(19)
  "DELIVERY_DAYS" int(10)
  "PM_CONDITION_ID" bigint(19)
  "ORDER_MONTH_NO" int(10)
  "CREATE_USER" bigint(19)
  "CREATE_DATE" datetime

  Checks {
    `[PARENT_QUOTATION_VER_LIN_ID] IS NULL OR [PARENT_QUOTATION_VER_LIN_ID]<>[QUOTATION_VER_LIN_ID]` [name: 'CK_SQ_VER_LIN_PARENT_NOT_SELF']
  }

  Indexes {
    (QUOTATION_VER_LIN_ID, LINE_NO, QUOTATION_VER_ID) [type: nonclustered, name: "IX_QT_VER_LIN_VER"]
    (QUOTATION_VER_ID, IS_PRESALES, IS_BOLD, LINE_TYPE) [type: nonclustered, name: "IX_SQ_VER_LIN_FLAGS"]
    QUOTATION_VER_ID [type: nonclustered, name: "IX_SQ_VER_LIN_VER"]
  }
}

Table "dbo"."OPPORTUNITY" {
  "OPPOR_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_DESC" varchar(150) [not null]
  "OPPOR_NUM" varchar(15) [not null]
  "OPPOR_NUM_INT" int(10)
  "CLIENTS_ID" bigint(19) [not null]
  "BUSINESS_LINE_ID" bigint(19)
  "WORKER_ID" bigint(19) [not null]
  "RESPONSIBLE_ID" bigint(19)
  "REASON_REJECTION_ID" bigint(19)
  "REASON_REJECTION" varchar(450)
  "CURRENCY_ID" bigint(19) [not null]
  "REGISTRATION_DATE" date
  "FINISH_DATE" date
  "CONSULT_DATE" datetime
  "QUO_DATE" datetime
  "OPPOR_AMOUNT" decimal(12,3)
  "PORCENT_PROGRESS_PRO" int(10)
  "PROCESS_NUM" int(10)
  "STATE_OPPORTUNITY_ID" bigint(19)
  "STATE_PRE_SALES_ID" bigint(19)
  "STATE_OPPOR_GEN_ID" bigint(19)
  "IS_PRE_OPPORTUNITY" bit
  "IS_OPPOR_MANAGER" bigint(19)
  "IS_APPROVED" bit
  "REJECTION_REASON" varchar(100)
  "DECISION_BY" bigint(19)
  "SUPERVISOR_ID" bigint(19)
  "SSOMA_ID" bigint(19)
  "TEC_LEADER_ID" bigint(19)
  "PROPOSAL_COMMENT" varchar(450)
  "WON_COMMENT" varchar(450)
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
  "LAST_STATE_CHANGE_AT" datetime
  "FOLLOWUP_ENABLED" bit
  "FOLLOWUP_EVERY_DAYS" int(10)
  "FOLLOWUP_NEXT_AT" datetime
  "PROPOSAL_TYPE_ID" bigint(19)
  "NEGOTIATION_OUTCOME_ID" bigint(19)
  "FOLLOWUP_SUSPENDED" bit
  "IS_TECH_ADMIN_APPROVED" bit
  "NEG_STAGES_ID" bigint(19)
}

Table "dbo"."OBS_STATUS" {
  "OBS_STATUS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19)
  "OBS_COLOR" varchar(150) [not null]
  "OBS_DESC" varchar(350) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."OPPORTUNITY_OBSERVATION" {
  "OBS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "OBS_TYPE" int(10) [not null]
  "OBS_SEVERITY" int(10) [not null]
  "OBS_STATUS_ID" bigint(19) [not null]
  "OBS_REASON" text [not null]
  "DUE_DATE" date [not null]
  "DUE_SET_BY" bigint(19) [not null]
  "OPENED_BY" bigint(19) [not null]
  "OPENED_AT" datetime [not null]
  "CLOSED_AT" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."OPPORTUNITY_STATE_HISTORY" {
  "HISTORY_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "FROM_STATE_OPPORTUNITY_ID" bigint(19)
  "TO_STATE_OPPORTUNITY_ID" bigint(19)
  "FROM_STATE_PRE_SALES_ID" bigint(19)
  "TO_STATE_PRE_SALES_ID" bigint(19)
  "FROM_STATE_OPPOR_GEN_ID" bigint(19)
  "TO_STATE_OPPOR_GEN_ID" bigint(19)
  "FROM_PROPOSAL_TYPE_ID" bigint(19)
  "TO_PROPOSAL_TYPE_ID" bigint(19)
  "FROM_NEGOTIATION_OUTCOME_ID" bigint(19)
  "TO_NEGOTIATION_OUTCOME_ID" bigint(19)
  "FROM_OBS_STATUS_ID" bigint(19)
  "TO_OBS_STATUS_ID" bigint(19)
  "CHANGE_REASON" varchar(550)
  "CHANGED_BY" bigint(19) [not null]
  "CHANGED_AT" datetime [not null]
}

Table "dbo"."LIC_STATUS" {
  "LIC_STATUS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "LIC_STATUS" varchar(150) [not null]
  "LIC_COLOR" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDTATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."OPPORTUNITY_LICITATION_REQUEST" {
  "LIC_REQ_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "LIC_STATUS_ID" bigint(19)
  "REQUEST_NOTE" text
  "REQUESTED_BY" bigint(19)
  "REQUESTED_AT" datetime
  "LICITATOR_ID" bigint(19) [not null]
  "REVIEWED_AT" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."OPPORTUNITY_INACTIVITY_SLA" {
  "SLA_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "STATE_OPPORTUNITY_ID" bigint(19) [not null]
  "INACTIVITY_HOURS" int(10) [not null]
  "ESCALATE_HOURS" int(10) [not null]
  "STATUS" char(1) [not null]
}

Table "dbo"."OBSERVATION_SLA" {
  "OBS_SLA_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OBS_TYPE" int(10) [not null]
  "OBS_SEVERITY" int(10) [not null]
  "SLA_HOURS" int(10) [not null]
  "ALERT_BEFORE_HOURS" int(10) [not null]
  "ESCALATE_HOURS" int(10) [not null]
  "STATUS" char(1) [not null]
}

Table "dbo"."ALERT_STATUS" {
  "ALERT_STATUS_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "ALERT_STATUS" varchar(150) [not null]
  "ALERT_COLOR" varchar(150) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Table "dbo"."OPPORTUNITY_ALERT_ACTION" {
  "ACTION_ID" bigint(19) [pk, not null, increment]
  "ALERT_ID" bigint(19) [not null]
  "BUSINESS_ID" bigint(19) [not null]
  "ACTION_TYPE" varchar(550)
  "ACTION_COMMENT" varchar(450)
  "SNOOZED_UNTIL" datetime2
  "ACTION_BY" bigint(19) [not null]
  "ACTION_AT" datetime2 [not null]
}

Table "dbo"."ALERT_TYPE" {
  "ALERT_TYPE_ID" int(10) [pk, not null, increment]
  "CODE" varchar(50) [not null]
  "NAME" varchar(100) [not null]
  "IS_BLOCKING" bit [not null, default: 0]
  "IS_ACTIVE" bit [not null, default: 1]
}

Table "dbo"."ALERT_SLA" {
  "ALERT_SLA_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "ALERT_TYPE_ID" int(10) [not null]
  "SLA_HOURS" int(10) [not null]
  "ESCALATE_LEVEL_1" bit [not null, default: 1]
  "ESCALATE_LEVEL_2" bit [not null, default: 0]
  "IS_ACTIVE" bit [not null, default: 1]
  "CREATED_AT" datetime [not null, default: `getdate()`]
}

Table "dbo"."OPPORTUNITY_ALERT" {
  "ALERT_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "OPPOR_ID" bigint(19) [not null]
  "ALERT_CODE" varchar(150)
  "SEVERITY_ID" bigint(19)
  "ALERT_STATUS_ID" bigint(19)
  "TARGET_USER_ID" bigint(19)
  "TITLE" varchar(150)
  "MESSAGE" varchar(350)
  "LINK_URL" varchar(750)
  "FIRST_TRIGGERED_AT" datetime2
  "LAST_TRIGGERED_AT" datetime2
  "NEXT_NOTIFY_AT" datetime2
  "SNOOZED_UNTIL" datetime2
  "RESOLVED_BY" bigint(19)
  "RESOLVED_AT" datetime2
  "STATUS" char(1) [not null]
}

Table "dbo"."NEGOTIATION_STAGES" {
  "NEG_STAGES_ID" bigint(19) [pk, not null, increment]
  "BUSINESS_ID" bigint(19) [not null]
  "NEG_DESC" varchar(350) [not null]
  "CREATE_USER" bigint(19) [not null]
  "CREATE_DATE" datetime [not null]
  "UPDATE_USER" bigint(19)
  "UPDATE_DATE" datetime
  "STATUS" char(1) [not null]
}

Ref "FK_AREAS_INTERNAL_VIS":"dbo"."VISIBILITY_TYPES"."VISIBILITY_ID" < "dbo"."AREA"."INTERNAL_VISIBILITY_ID"

Ref "FK_AUDIT_EVENT_DIFF_EVENT":"dbo"."AUDIT_EVENT"."EVENT_ID" < "dbo"."AUDIT_EVENT_DIFF"."EVENT_ID"

Ref "FK__NOTIF_RUL__RULE___5A6F5FCC":"dbo"."NOTIF_RULES"."RULE_ID" < "dbo"."NOTIF_RULE_FILTERS"."RULE_ID"

Ref "FK_OCA_COMMENT":"dbo"."OPPOR_COMMENTS"."COMMENT_ID" < "dbo"."OPPOR_COMMENT_AUDIENCE"."COMMENT_ID" [delete: cascade]

Ref "FK_SQ_EGRESS_VER_HDR":"dbo"."SALES_QUOTATION_VER_HDR"."QUOTATION_VER_ID" < "dbo"."SALES_QUOTATION_EGRESS_VER_HDR"."QUOTATION_VER_ID"

Ref "FK_SQ_EGRESS_VER_LIN":"dbo"."SALES_QUOTATION_EGRESS_VER_HDR"."EGRESS_VER_ID" < "dbo"."SALES_QUOTATION_EGRESS_VER_LIN"."EGRESS_VER_ID"

Ref "FK_SQ_LINE_PLAN_HDR":"dbo"."SALES_QUOTATION_VER_LIN"."QUOTATION_VER_LIN_ID" < "dbo"."SALES_QUOTATION_LINE_PLAN_VER_HDR"."QUOTATION_VER_LIN_ID"

Ref "FK_SQ_LINE_PLAN_LIN":"dbo"."SALES_QUOTATION_LINE_PLAN_VER_HDR"."LINE_PLAN_ID" < "dbo"."SALES_QUOTATION_LINE_PLAN_VER_LIN"."LINE_PLAN_ID"

Ref "FK_SQ_MARGIN_VER":"dbo"."SALES_QUOTATION_VER_HDR"."QUOTATION_VER_ID" < "dbo"."SALES_QUOTATION_MARGIN_VER"."QUOTATION_VER_ID"

Ref "FK_SQ_SERVICE_CHECK_VER":"dbo"."SALES_QUOTATION_VER_HDR"."QUOTATION_VER_ID" < "dbo"."SALES_QUOTATION_SERVICE_CHECK_VER"."QUOTATION_VER_ID"

Ref "FK_SALES_QUOTATION_VER_HDR_QUOTATION":"dbo"."SALES_QUOTATION_HDR"."QUOTATION_ID" < "dbo"."SALES_QUOTATION_VER_HDR"."QUOTATION_ID"

Ref "FK_SQ_VER_LIN_VER":"dbo"."SALES_QUOTATION_VER_HDR"."QUOTATION_VER_ID" < "dbo"."SALES_QUOTATION_VER_LIN"."QUOTATION_VER_ID"
