export const SUB_BY_ARCHIVE_TYPE: Record<string, string[]> = {
  //CARPETAS PRINCIPALES
  LOGISTICA: ["LOGISTICA"],
  TECNICA: ["TECNICA"],

  //SUB CARPETAS
  /*===================PRESUPUESTAL===================*/
  OPERATIONS: ["PRESUPUESTAL","OPERACIONES"],
  LOGISTICS: ["PRESUPUESTAL","LOGISTICA"],
  CLEINTS: ["PRESUPUESTAL","CLIENTES"],
  /*===================CONTRATACIONES===================*/
  CONSULTORIA: ["CONTRATACIONES", "CONSULTORIA"],
  DOCUMENTACION: ["CONTRATACIONES", "DOCUMENTACION"],
  INFORMES: ["CONTRATACIONES", "INFORMES"],

  /*===================ECONOMICA===================*/
  FACTURACION: ["ECONOMICA", "FACTURACION"],
  GUIAS_FIRMADAS: ["ECONOMICA", "GUIAS-FIRMADAS"],
  COMPROBANTES_PAGO: ["ECONOMICA", "COMPROBANTES-PAGO"],
  ACTAS_CONFORMIDAD: ["ECONOMICA", "ACTAS-CONFORMIDAD"],
};
