export interface SuppliersResponseDto {
  suppliersId?: number;
  businessId?: number;
  supplierTypeId?: number;
  suppliersGroupsId?: number;
  supplierGroupsId?: number;
  documentTypeId?: number;
  paymentConditionId?: number;
  paymentMethodId?: number;
  departamentId?: number | null;
  departmentId?: number | null;
  provinceId?: number | null;
  districtId?: number | null;
  suppliersTypeDesc?: string;
  typeSuppliersDesc?: string;
  typeSuppliersLabel?: string;
  suppliersGroupDesc?: string;
  suppliersGroupsDescription?: string;
  documentTypeDescription?: string;
  paymentTypeDescription?: string;
  paymentMethodDescription?: string;
  departamentDescription?: string;
  departmentDescription?: string;
  provinceDescription?: string;
  districtDescription?: string;
  supplierName?: string;
  tradeName?: string;
  documentNumber?: string;
  contactName?: string;
  address?: string;
  phone?: string;
  mobile?: string;
  movil?: string;
  email?: string;
  website?: string;
  paymentMethodDesc?: string;
  paymentConditionDesc?: string;
  paymentConditionDescription?: string;
  retainerAgent?: boolean | string;
  perceptionAgent?: boolean | string;
  detractionAgent?: boolean | string;
  foreignAgent?: boolean | string;
  observation?: string;
  status?: string | boolean;
  suppliersCount?: number;
}
